### ISSUE TITLE
Re: Sean O'Connor

### ISSUE THREAD

**Issue by ghost** [akanimax/my-deity#1]
Hi Animesh,
The evolutionary algorithm I use is here: 
https://forum.processing.org/two/discussion/23422/a-simple-way-to-optimize
I don't know if that is useful for you.

Sean O'Connor

**Comment by akanimax** [comment]
Thank you. I'll surely go through it.

**Comment by ghost** [comment]
Neural network allowing complicated interconnects and modules to spontaneously evolve:
https://github.com/S6Regen/Data-Reservoir-Compute-AI

**Comment by akanimax** [comment]
Thank you for the discussion. Closing the issue now.
