### ISSUE TITLE
Your deity is too weak in weight space to be God worthy

### ISSUE THREAD

**Issue by JordanMicahBennett** [akanimax/my-deity#2]
OP, your concept doesn't even utilize [Supersymmetry](https://github.com/JordanMicahBennett/Supersymmetric-artificial-neural-network).

1. By the way, [my "God"](https://github.com/JordanMicahBennett/God) is Edward Witten inspired, and thus richer in weight space.

2. Your ["deity"](https://github.com/akanimax/my-deity) is still using real numbers in weight space. Why stop at real numbers when better things exist such as: [unitaryRNNs](https://arxiv.org/abs/1612.05231), or [Deep Complex Nets](https://arxiv.org/abs/1705.09792) or reasonably my ["Supersymmetric Artificial Neural Network"](https://github.com/JordanMicahBennett/Supersymmetric-artificial-neural-network)?

3. Your ["deity"](https://github.com/akanimax/my-deity) appears to lack inclusion of reinforcement learning, which has been demonstrated by Deepmind to be pertinent in describing their general learning algorithm "AlphaZero".

4. Deities as defined [within the realm of artificial general intelligence](https://m.youtube.com/watch?feature=youtu.be&t=849&v=8nt3edWLgIg) ought ***not*** to be worshipped and [ought to be atheism compatible](https://www.researchgate.net/publication/316662636_A_scientific_redefinition_of_God_by_an_atheist)!!

**Comment by akanimax** [comment]
Thank you for the insights. The deity will eventually gain enough power simultaneously as I keep gaining the knowledge of this field. :+1: 
:)

**Comment by JordanMicahBennett** [comment]
The idea about black holes as absolute minima is somewhat intriguing.

Anywat, does your deity include considerations for reinforcement learning?

**Comment by JordanMicahBennett** [comment]
Newton's methods [already occur](https://dl.acm.org/citation.cfm?id=1273567) in machine learning, for quite a long while now.

Remember to try to get a broad view of machine learning before attempting to "invent" things. 

This way you are perhaps better prepared to avoid relabelling prior prominent work.

Examples of ways to observe neural nets as a whole:

1. [Short 4 line deep neural net overview in terms of groups ranging from Integer based weight space to convolving complex weight space](https://www.quora.com/How-can-I-learn-the-big-picture-of-Machine-Learning-Between-Neural-Nets-SVMs-GANs-Reinforcement-etc-is-there-any-systematic-approach-I-can-take-to-understand-and-get-a-general-idea-of-all/answer/Jordan-Bennett-9/).

2. [Short 5 line overview of deep neural net in terms of groups ranging from orthogonal to special unitary grouping]( https://www.quora.com/How-far-are-we-from-achieving-artificial-general-intelligence-AGI/answer/Jordan-Bennett-9/).

**Comment by akanimax** [comment]
@JordanMicahBennett Thanks for the suggestion. Will consider it further.

**Comment by akanimax** [comment]
Hi @JordanMicahBennett , I was looking into Networks that use complex numbers in the weight-space. I came across these two submissions at the 2018 ICLR -> [deep complex networks](https://openreview.net/forum?id=H1T2hmZAb) and [complex and real valued](https://openreview.net/forum?id=H1S8UE-Rb). However, the reviews are not too good, and the primary need of using complex numbers in neural networks has been questioned by the reviewers. Probably will be rejected.

Another case is that the concept of RNN itself is being questioned highly by the researches such as -> [AIAYN](https://arxiv.org/abs/1706.03762), [ConvSeq2Seq](https://arxiv.org/abs/1705.03122), [CIAYN](https://arxiv.org/abs/1712.09662). So, mixing RNNs with complex numbers, I don't perceive as a good idea. 

The most important principle of my research is simplicity. Thank you for all the suggestions that you provided me with; it really helped me gain more insights in this field. The deity has definitely become more powerful, Thanks to you!

**Comment by JordanMicahBennett** [comment]
The [Deep Complex network paper](https://arxiv.org/abs/1705.09792)  by Yoshua Bengio et al probably wont be rejected, for the simple reasons below:

1. In [Deep learning](https://en.wikipedia.org/wiki/Deep_learning), it is typical for researchers to seek structures that can represent more information in weight space.

2. **Real-valued** [convolutional neural nets](https://en.wikipedia.org/wiki/Convolutional_neural_network) can trivially store **magnitude information**.

3. **Complex-valued** [convolutional neural nets](https://en.wikipedia.org/wiki/Convolutional_neural_network) can trivially store **phase information, in addition to magnitude information**. (As seen in the [Deep Complex network paper](https://arxiv.org/abs/1705.09792))

4. So, seeking methods for representing more information in weight space, is a sensible, and typical goal in [Deep learning](https://en.wikipedia.org/wiki/Deep_learning), because the richer your weight space, the better the hypotheses or answers produced by neural net models!

**Note:** [Professor Yoshua Bengio](https://en.wikipedia.org/wiki/Yoshua_Bengio), (chairman for [ICLR](http://www.iclr.cc/doku.php?id=iclr2018:main)), who co-authored the [Deep Complex network paper](https://arxiv.org/abs/1705.09792) is a pioneer in the [Deep learning](https://en.wikipedia.org/wiki/Deep_learning) field, so his papers and collaborations are quite sensible!

**Comment by akanimax** [comment]
closing the issue
